spring:
  datasource:
    url: jdbc:h2:file:./data/exemplo # Armazenamento em arquivo no diretório 'data'
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update  # Use 'update' para atualizar o esquema do banco de dados
  h2:
    console:
      enabled: true
      path: /h2
      